'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Actualizar_Fecha_Promo

    '''<summary>
    '''UP0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP0 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''P0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P0 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''T0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T0 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''TXTDEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTDEL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTAL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNRUN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNRUN As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNENC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNENC As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNDET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNDET As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''GVREP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVREP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BTNEXPORT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNEXPORT As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TXTPROMO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTPROMO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTDESCRIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTDESCRIP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTINICIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTINICIO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTFINAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTFINAL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTTIPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTTIPO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTDESCUENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTDESCUENTO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTASOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTASOC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBLERR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLERR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BTNGRD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNGRD As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNBACK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNBACK As Global.System.Web.UI.WebControls.LinkButton
End Class
