'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Bitacora

    '''<summary>
    '''UP0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP0 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HF01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF01 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''P0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P0 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TXTDEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTDEL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTAL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNFLT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNFLT As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''GVBIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVBIT As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ADDNEW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ADDNEW As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DDLEMPRESABITACORA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLEMPRESABITACORA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLTIENDABITACORA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLTIENDABITACORA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLEMPLEADOBITACORA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLEMPLEADOBITACORA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLCATALOGOBITACORA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLCATALOGOBITACORA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXTSOL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTSOL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTDES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTDES As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNADDACT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNADDACT As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LTESTADO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTESTADO As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CLOSEACT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLOSEACT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''L02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L02 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ADDSEG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ADDSEG As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BTNCANCELARSEGUIMIENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNCANCELARSEGUIMIENTO As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LTNOACTIVIDAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTNOACTIVIDAD As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TXTSOL1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTSOL1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTDESC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTDESC1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNPROCESARSEGUIMIENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNPROCESARSEGUIMIENTO As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LTNOACTIVIDAD_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LTNOACTIVIDAD_ As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TXTCOMENTCIERRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTCOMENTCIERRE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNCERRARACTIVIDAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNCERRARACTIVIDAD As Global.System.Web.UI.WebControls.LinkButton
End Class
