'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Calendario_Tiendas

    '''<summary>
    '''UP0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP0 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''P0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P0 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''BTNGENERAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNGENERAR As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNNEW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNNEW As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TXTSUPER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTSUPER As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXTSEMANA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTSEMANA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXTTIENDAS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTTIENDAS As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBLERR7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLERR7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLERR9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLERR9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLERR8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLERR8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLCALENDARIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLCALENDARIO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLCALENDARIO1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLCALENDARIO1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GVREP0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVREP0 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GVREP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVREP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BTNEXPORT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNEXPORT As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''T1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''TXTBUSQUEDA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTBUSQUEDA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTVENDEDOR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTVENDEDOR As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXTTIENDA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTTIENDA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXTSUPERVISOR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTSUPERVISOR As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DPDSMN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DPDSMN As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBLERR1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLERR1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BTNBACK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNBACK1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNADD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNADD As Global.System.Web.UI.WebControls.LinkButton
End Class
