'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConfSap

    '''<summary>
    '''UP0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP0 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''BTNOUT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNOUT As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNINT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNINT As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TXTSRVSQL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTSRVSQL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTDBBSQL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTDBBSQL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTUSRSQL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTUSRSQL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTPWDSQL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTPWDSQL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTUSRSAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTUSRSAP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTPWDSAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTPWDSAP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTEMPSAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTEMPSAP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ERRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ERRM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BTNSAV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNSAV As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''UP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP1 As Global.System.Web.UI.UpdateProgress
End Class
