'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Consumo_respuesto_flotilla

    '''<summary>
    '''P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''L01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L01 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DDLSERIEDOCTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLSERIEDOCTO As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXTNODOCTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTNODOCTO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDLCLIENTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLCLIENTE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXTFECHADOCUMENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTFECHADOCUMENTO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTEQUIPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTEQUIPO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTSERIE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTSERIE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTHOROMETROCRF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTHOROMETROCRF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTTECNICOSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTTECNICOSN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDLCD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLCD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''P1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1_1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLTIPOCONSULTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLTIPOCONSULTA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXTDATOBUSQUEDA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTDATOBUSQUEDA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNBUSCARPARTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNBUSCARPARTE As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''GVPARTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVPARTE As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ImageButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton2 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''P1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1_2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''BTNHABILITARBUSQUEDA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNHABILITARBUSQUEDA As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''GVCONSUMOPARTES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVCONSUMOPARTES As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SQLCONSUMOPARTES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SQLCONSUMOPARTES As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''BTNADD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNADD As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNCANHS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNCANHS As Global.System.Web.UI.WebControls.LinkButton
End Class
