'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Empleados

    '''<summary>
    '''DDLAREA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLAREA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SQLEMPLEADO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SQLEMPLEADO As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SQLTIPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SQLTIPO As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SQLENCARGADO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SQLENCARGADO As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PANELEMPLEADO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PANELEMPLEADO As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GVEMPLEADO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVEMPLEADO As Global.System.Web.UI.WebControls.GridView
End Class
