'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Interfaz

    '''<summary>
    '''UP0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP0 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''P01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P01 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''BTNOUT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNOUT As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNCFG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNCFG As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TXTORIG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTORIG As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXTDEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTDEL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTAL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNGO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNGO As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''UP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''LBLTITLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLTITLE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ERRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ERRM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GVVTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVVTA As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BTNEXPORT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNEXPORT As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''LBLBTNSAPERR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLBTNSAPERR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BTNSAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNSAP As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LSAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LSAP As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''P02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P02 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''BTNDBCK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNDBCK As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TITDET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TITDET As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TXTFTDA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTFTDA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXTFDEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTFDEL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTFAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTFAL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNFGO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNFGO As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''GVDET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVDET As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BTNEXPOR2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNEXPOR2 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''T0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T0 As Global.System.Web.UI.Timer
End Class
