'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class REP_PLANTA

    '''<summary>
    '''UP0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP0 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''HS01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HS01 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''P0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P0 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TXTFDEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTFDEL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTFAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTFAL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNGO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNGO As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''GVREP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVREP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BTNEXPORT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNEXPORT As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''L01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L01 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TXTHORO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTHORO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTDP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTDT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTDT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTSE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTSE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTNS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTNS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTTSALIDA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTTSALIDA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTTLLEGADA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTTLLEGADA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTSINICIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTSINICIO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXTSFINAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTSFINAL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBLERRM01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLERRM01 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BTNADDHS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNADDHS As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNCANHS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNCANHS As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BTNFIRMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNFIRMA As Global.System.Web.UI.WebControls.LinkButton
End Class
