'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Rpt_Digitacion

    '''<summary>
    '''btnpanelopciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnpanelopciones As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''id01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id01 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SP01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SP01 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''DDLREPORTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLREPORTE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLEMPRESA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLEMPRESA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLTIENDA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLTIENDA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXTFECHADOCTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTFECHADOCTO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTNGO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNGO As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''P_IMAGENES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P_IMAGENES As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''IMGDOCTO_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IMGDOCTO_ As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''GVREP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVREP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''P_DOCTODETA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P_DOCTODETA As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GVDOCTODETA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVDOCTODETA As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''P_DOCTOENCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P_DOCTOENCA As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GVDOCTOENCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVDOCTOENCA As Global.System.Web.UI.WebControls.GridView
End Class
