'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Ventas_Conciliacion

    '''<summary>
    '''SQLDETCONCILIACION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SQLDETCONCILIACION As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PANELORDENCOMPRA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PANELORDENCOMPRA As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GVDETCONCILIACION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVDETCONCILIACION As Global.System.Web.UI.WebControls.GridView
End Class
